(println (if #t 1 2))
(println (if #f 1 2))
(println (begin (define x 10) (+ x 5)))
(println (let ((y 20)) (+ y 10)))
(println (and #t #t #t))
(println (and #t #f #t))
(println (or #f #f #t))
(println (or #f #f #f))
